const router = require('express').Router();
const { protect } = require('../middleware/authMiddleware');
const permission = require('../middleware/leadTypePermission');
const controller = require('../controllers/leadTypeController');
router.use(protect);
router.get('/', permission('view'), controller.list);
router.post('/', permission('edit'), controller.create);
router.put('/:id', permission('edit'), controller.update);
router.delete('/:id', permission('delete'), controller.remove);
module.exports = router;
